### ISSUE TITLE
The JS for the Subtabs is not working in the Theme Options

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-blog-customizer#8]
If you do not have LSX banners installed, and the LSX Blog Customizer, than the UI JS comes from the Customizer plugin.

We need to compare the version in the Blog Customizer to the LSX Banners one, and copy across any updates.

[Example Site](https://gutenberg.feedmybeta.com/wp-admin/themes.php?page=lsx-settings#ui-sharing)

**Comment by jacquesvdhorst** [comment]
@krugazul I've tested this with Blog Customizer and Testimonials installed so I have access to sub tabs in the options and it seems to be working fine. js is being called from the blog customizer and tabs are clickable. This was done on a clean install:

![image](https://user-images.githubusercontent.com/35291167/66816582-9f398780-ef3a-11e9-9c4b-f2e5f977a827.png)

**Comment by jacquesvdhorst** [comment]
Tested again on a clean install doesn't seem to be doing this anymore.
